# Exercise 1
Convert a 1D array to a 2D array with 2 rows
<pre>arr=np.arange(10)</pre>
<br>
We want:  
<pre>
array([[0, 1, 2, 3, 4],
	   [5, 6, 7, 8, 9]])
</pre>

In [3]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
[.1+.1+.1, .1+.1] == [.3, .2]
[.1+.1+.1, .1+.1]
[.3, .2]
np.allclose([.1+.1+.1, .1+.1], [.3, .2])

False

[0.30000000000000004, 0.2]

[0.3, 0.2]

True

# Exercise 2

Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

# Exercise 3

Given the following array:
    
<pre>arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])</pre>

Create an array composed of the 3rd column of each row of `arr`

# Exercise 4

Create an 8X3 integer array from a range between 10 to 34.

Then Split the array into four equal-sized 2x3 sub-arrays.

# Exercise 5

Given the array:

    arr = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

delete it's second column.

Then, using the method `insert()` insert the following new column as the second column:

    col = np.array([[10,10,10]])

# Exercise 6

Replace all odd numbers in arr with -1 without changing arr and then by changing arr

<pre>arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])</pre>


# Exercise 7

How to get the positions where elements of two arrays match?

<pre>
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
</pre>

# Exercise 8

How to remove from one array those items that exist in another?

<pre>
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
</pre>

# Exercise 9

How to stack two arrays horizontally
<pre>
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
</pre>
We want:  
<pre>
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
 		[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
</pre>

# Exercise 10

Get all items between 5 and 10 from a

<pre>
a = np.array([2, 6, 1, 9, 10, 3, 27])
</pre>

# Exercise 11

Swap columns 1 and 2 in the array arr

<pre>
arr = np.arange(9).reshape(3,3)
</pre>

# Exercise 12

How to find the count of unique values in the numpy array a?

<pre>
a = np.array([1,2,2,1,2,5])
</pre>

# Exercise 13

Create a UFunc that will be able to **normalize** the array it receives as argument.

To normalize a value, subtract it from the minimum value of the dataset and divide it by using the difference between the maximum and minimum value of the dataset.
The lowest value in the data will have the value 0 and the highest value in the data will have the value 1 and the other values will be within the range 0 and 1.
