# Numpy and Numpy Arrays

## <a href="#0">0 Preamble: A note about Jupyter notebooks</a>

## <a href="#I">I Arrays</a>
### <a href="#I.1">I.1 Creating Arrays</a>
#### <a href="#I.1.1">I.1.1 From Python sequences</a>
#### <a href="#I.1.1">I.1.2 Other ways to construct an Array</a>
### <a href="#I.2">I.2 Array's attributes</a>
### <a href="#I.3">I.3 Reshaping of Arrays</a>
### <a href="#I.4">I.4 Arrays and Axes</a>
## <a href="#II">II Indexing and slicing</a>
### <a href="#II.1">II.1 Indexing Arrays</a>
#### <a href="#II.1.1">II.1.1 Random functions and seeds</a> 
### <a href="#II.2">II.2 Slicing Arrays</a>
#### <a href="#II.2.1">II.2.1 Slicing One-dimensional arrays</a>
#### <a href="#II.2.2">II.2.2 Slicing Multi-dimensional arrays</a>
#### <a href="#II.2.3">II.2.3 Accessing rows and columns of matrices</a>
#### <a href="#II.2.4">II.2.4 Slices are views</a>
### <a href="#II.3">II.3 Fancy Indexing</a>
#### <a href="#II.3.1">II.3.1 A first example</a>
#### <a href="#II.3.2">II.3.2 Indexing with a list of integers</a>

## <a href="#III">III Concatenation/Splitting of arrays</a>
### <a href="#III.1">III.1 Concatenation of arrays</a>
### <a href="#III.2">III.2 Splitting of arrays</a>

## <a href="#IV">IV Universal functions (ufuncs)</a>
### <a href="#IV.1">IV.1 Numerical operations on arrays</a>
#### <a href="#IV.1.1">IV.1.1 Arithmetic operations on arrays</a>
#### <a href="#IV.1.2">IV.1.2 Absolute value</a>
#### <a href="#IV.1.3">IV.1.3 Trigonometric functions</a>
#### <a href="#IV.1.4">IV.1.4 Exponents and logarithms</a>
#### <a href="#IV.1.5">IV.1.5 Other Ufuncs</a>
### <a href="#IV.2">IV.2 Advanced Ufunc Features</a>
#### <a href="#IV.2.1">IV.2.1 Specifying output</a>
#### <a href="#IV.2.2">IV.2.2 Aggregates</a>
#### <a href="#IV.2.3">IV.2.3 Outer products</a>

## <a href="#V">V Broadcasting</a>
### <a href="#V.1">V.1 First examples</a>
### <a href="#V.2">V.2 Broadcasting rules</a>

## <a href="#VI">VI Boolean Masking of Arrays</a>
### <a href="#VI.1">VI.1 Comparison Operators as ufuncs</a>
### <a href="#VI.2">VI.2 Working with Boolean Arrays</a>
### <a href="#VI.3">VI.3 Boolean Operators</a>
### <a href="#VI.4">VI.4 Boolean Arrays as Masks</a>

## <a href="#VII">VII Basic Linear Algebra Operations</a>
### <a href="#VII.1">VII.1 Dot product</a>
### <a href="#VII.2">VII.2 Transpose of a matrix</a>
### <a href="#VII.3">VII.3 Inverse of a Matrix</a>
### <a href="#VII.4">VII.4 Matrix Multiplication</a>
### <a href="#VII.5">VII.5 And also</a>

## <a href="#VIII">VIII NumPy Aggregate Functions</a>
### <a href="#VIII.1">VIII.1 Minimum and Maximum</a>
### <a href="#VIII.2">VIII.2 Other aggregate functions</a>

## <a href="#IX">IX Some other useful functions</a>
### <a href="#IX.1">IX.1 where</a>
### <a href="#IX.2">IX.2 repeat</a>
### <a href="#IX.3">IX.3 tile</a>
### <a href="#IX.4">IX.4 delete</a>
### <a href="#IX.5">IX.5 unique</a>
### <a href="#IX.6">IX.6 setdiff1d</a>

<a id="0"></a>
## 0. Preamble: A note about Jupyter notebooks

By finishing a Jupyter cell with the name of a variable or unassigned output of a statement, Jupyter will display that variable without the need for a print statement. This is especially useful when dealing with Pandas DataFrames, as the output is neatly formatted into a table.


You can modify the __ast_note_interactivity__ kernel option to make Jupyter do this for any variable or statement on it’s own line, so you can see the value of multiple statements at once: place this code in a Jupyter cell:

In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all" # default is 'last'

If you want to set this behaviour for all instances of Jupyter, simply create a file __~/.ipython/profile_default/ipython_config.py__ with the lines below:


<pre>
c = get_config()

c.InteractiveShell.ast_node_interactivity = "all"
</pre>

__Note__: with the default mode `last`, you can put a semicolon (`;`) at the end of the last command to suppress its output.


<a id="I"></a>
## I. Arrays

__Numpy__ is the core library for scientific computing in Python. It provides a high-performance multidimensional array object (__ndarray__), and tools for working with these arrays. <br>
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non_negative integers. 

While Python lists and numpy arrays have similarities in that they are both collections of values that use indexing to help you store and access data, there are a few key differences between these two data structures:

1. Unlike a Python list, all elements in a numpy arrays __must be the same data type__ (i.e. all integers, decimals, text strings, etc).<br>

2. Because of this requirement, numpy arrays support arithmetic and other mathematical operations that run on each element of the array (e.g. element-by-element multiplication). <br>

3. Numpy arrays can store data along multiple dimensions (e.g. rows, columns) that are relative to each other. This makes numpy arrays a very efficient data structure for large datasets.<br>

4. Numpy arrays take up less space than lists.<br>

5. Numpy arrays are much faster than lists.<br>

<a id="I.1"></a>
### I.1 Creating Arrays
<a id="I.1.1"></a>
#### I.1.1 From Python sequences

We can use __np.array()__ to create arrays from Python sequences (list, tuple, ...).<br>

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (integers to floating point for instance ...).

If we want to explicitly set the data type of the resulting array, we can use the __dtype__ keyword argument of _np.array()_.

In [1]:
import numpy as np

# integer array:
np.array([1, 4, 2, 5, 3])
# float array (implicitely):
np.array((3.14, 4, 2, 3))
# float array:
np.array([1, 2, 3, 4], dtype='float32')

array([1, 4, 2, 5, 3])

array([3.14, 4.  , 2.  , 3.  ])

array([1., 2., 3., 4.], dtype=float32)

Unlike Python lists, NumPy arrays can explicitly be multi-dimensional; one way of initializing a multidimensional array is to use a list of lists

In [20]:
# nested lists result in multi-dimensional arrays
np.array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])
# The inner lists are treated as rows of the resulting two-dimensional array

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

NumPy arrays contain values of a single type, the standard NumPy data types are listed in the following table. 

Note that when constructing an array, they can be specified with the keyword argument **dtype** using a string:
**dtype='int16'** 
or the associated NumPy object:
**dtype=np.int16**

<table border=1>
<tr><th>Data type</th>	<th>Description</th></tr>
<tr><td style="text-align:left"><b>bool_</b></td><td style="text-align:left">	Boolean (True or False) stored as a byte</td></tr>
<tr><td style="text-align:left"><b>int_</b></td><td style="text-align:left">	Default integer type (same as C long; normally either int64 or int32)</td></tr>
<tr><td style="text-align:left"><b>intc</b></td><td style="text-align:left">	Identical to C int (normally int32 or int64)</td></tr>
<tr><td style="text-align:left"><b>intp</b></td><td style="text-align:left">	Integer used for indexing (same as C ssize_t; normally either int32 or int64)</td></tr>
<tr><td style="text-align:left"><b>int8</b></td><td style="text-align:left">	Byte (-128 to 127)</td></tr>
<tr><td style="text-align:left"><b>int16</b></td><td style="text-align:left">	Integer (-32768 to 32767)</td></tr>
<tr><td style="text-align:left"><b>int32</b></td><td style="text-align:left">	Integer (-2147483648 to 2147483647)</td></tr>
<tr><td style="text-align:left"><b>int64</b></td><td style="text-align:left">	Integer (-9223372036854775808 to 9223372036854775807)</td></tr>
<tr><td style="text-align:left"><b>uint8</b></td><td style="text-align:left">	Unsigned integer (0 to 255)</td></tr>
<tr><td style="text-align:left"><b>uint16</b></td><td style="text-align:left">	Unsigned integer (0 to 65535)</td></tr>
<tr><td style="text-align:left"><b>uint32</b></td><td style="text-align:left">	Unsigned integer (0 to 4294967295)</td></tr>
<tr><td style="text-align:left"><b>uint64</b></td><td style="text-align:left">	Unsigned integer (0 to 18446744073709551615)</td></tr>
<tr><td style="text-align:left"><b>float_</b></td><td style="text-align:left">	Shorthand for float64.</td></tr>
<tr><td style="text-align:left"><b>float16</b></td><td style="text-align:left">	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa</td></tr>
<tr><td style="text-align:left"><b>float32</b></td><td style="text-align:left">	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa</td></tr>
<tr><td style="text-align:left"><b>float64</b></td><td style="text-align:left">	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa</td></tr>
<tr><td style="text-align:left"><b>complex_</b></td><td style="text-align:left">	Shorthand for complex128.</td></tr>
<tr><td style="text-align:left"><b>complex64</b></td><td style="text-align:left">	Complex number, represented by two 32-bit floats</td></tr>
<tr><td style="text-align:left"><b>complex128</b></td><td style="text-align:left">	Complex number, represented by two 64-bit floats</td></tr>
<table>

<a id="I.1.2"></a>
#### I.1.2 Other ways to construct an Array

Most of the time, it is more efficient to create arrays from scratch using routines built into NumPy (__zeros()__, __one()__, __full()__, __arange()__, __linspace()__, __random()__, __randint()__, __normal()__, __empty()__, __eye()__, ...) than via the `array()` constructor.<br>

Most of these methods take an int (the number of elements) or a tuple of ints (the shape of the array) as argument and optionnaly the _dtype_ of the array elements.

In [3]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

# Create an array filled with a linear sequence
# Starting at 1.5, ending at 16.5, stepping by 0.5
np.arange(1.5, 16.5, 0.5)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

# Create a 3x3 identity matrix
np.eye(3)

# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

array([ 1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,
        7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. ,
       12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

array([[0.73383705, 0.9709269 , 0.52679218],
       [0.69558902, 0.10950746, 0.9937082 ],
       [0.38363222, 0.89953382, 0.63407946]])

array([[-0.72599125,  0.53355241, -0.56007113],
       [-1.23842829,  0.20497493,  0.08561847],
       [ 0.10401849, -0.07056037,  1.15575714]])

array([[7, 4, 7],
       [3, 2, 0],
       [5, 3, 5]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([1., 1., 1.])

<a id="I.2"></a>
### I.2 Array's attributes

Each array has the following attributes:

__ndim__ : (ro) the number of dimensions, 

__shape__ : (rw) the size of each dimension, 

__size__ : (ro) the total number of elements in the array, 

__dtype__ : (ro) the data type of the array's elements.

In [3]:
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x2
x2.shape
x2.ndim
x2.dtype
x2.size
np.sum(x2)
np.sum(x2, axis=0)
np.sum(x2, axis=1)

array([[9, 6, 1, 9],
       [2, 8, 5, 8],
       [1, 4, 0, 3]])

(3, 4)

2

dtype('int32')

12

56

array([12, 18,  6, 20])

array([25, 23,  8])

<a id="I.3"></a>
### I.3 Reshaping of Arrays

The standard way of reshaping an array is to use the __reshape()__ method.
For this to work, the size of the initial array must match the size of the reshaped array.
For example, if you want to put the numbers 1 through 9 in a 3x3 matrix, you can do the following:

In [2]:
values = np.arange(1, 10)
values
values.shape
mat=values.reshape((3, 3))
mat
mat.shape

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

(9,)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

(3, 3)

Reshaping can be used to convert a one-dimensional array into a two-dimensional matrix. This can be done with the _reshape()_ method, or by making use of the __newaxis__ value within a slice:

In [7]:
x = np.array([1, 2, 3])
x
# row vector via reshape
mat1=x.reshape((1, 3))
mat1
# row vector via np.newaxis and the slice operator
mat2=x[np.newaxis, :]
mat2
# column vector via reshape
mat1=x.reshape((3, 1))
mat1
mat1.shape
# row vector via np.newaxis and the slice operator
mat2=x[:, np.newaxis]
mat2
mat2.shape

array([1, 2, 3])

array([[1, 2, 3]])

array([[1, 2, 3]])

array([[1],
       [2],
       [3]])

(3, 1)

array([[1],
       [2],
       [3]])

(3, 1)

<a id="I.4"></a>
### I.4 Arrays and Axes

NumPy <b>axes</b> are very similar to axes in a Cartesian coordinate system.<br>
A simple 2-dimensional Cartesian coordinate system has two axes, the x axis and the y axis.<br>
In a 2-dimensional numpy array, axes are the directions along the rows (axis 0) and the columns (axis 1).<br>
<b>Note</b>: numpy array axes are numbered starting with 0.
<img src="nbimages/numpy-axes.png" alt="Axes" title="Axes" width=300 height=200 />
Several Numpy functions take an <b>axis</b> parameter, to understand how to use this parameter, it is important to understand what the axis parameter actually controls for each function. <br><br>
For example, in the <b>np.sum()</b> function (see § IV.2.2), the axis parameter behaves in a way that many people think is counter intuitive.<br>

<b>np.sum()</b> effectively aggregates your data: doing a summation, it collapses several values into a single value.<br>
When you use <b>np.sum()</b> on a 2-d array it is going to collapse your 2-d array down to a 1-d array. 
It will collapse the data and reduce the number of dimensions.
<br>
In <b>np.sum()</b>, the <b>axis</b> parameter allows you to specify <b>the axis that gets collapsed</b>.<br>

For instance, when we set <b>axis = 0</b>, we are aggregating the data such that we collapse the rows: we collapse axis 0. We are not summing across the rows!<br>

Functions like <b>mean()</b>, <b>min()</b>, <b>median()</b>, and other statistical functions aggregate your data in the same way as <b>sum()</b> using the axis parameter.<br>

Another example of the use of axis parameter is the NumPy <b>concatenate()</b> function.<br>

With the <b>np.concatenate()</b> function (see § III.1), the <b>axis</b> parameter defines the axis along which we stack the arrays. 

So when we set axis = 0, we’re telling the <b>concatenate</b> function to stack the two arrays along the rows: we stack them vertically.<br>

When we use Numpy <b>concatenate()</b> with axis = 1, we are telling the <b>concatenate()</b> function to combine these arrays together horizontally, since axis 1 is the axis that runs horizontally across the columns.<br>

<a id="II"></a>
## II Indexing and slicing

<a id="II.1"></a>
### II.1 Indexing 
The items of an array can be accessed and assigned to the same way as other sequences (indices begin at 0):

In [12]:
np.random.seed(3) # to generate each time the same random numbers
a = np.random.randint(0, 21, 10)
a
a[0]
a[-1]
a[2]=888
a

array([ 5, 20, 17, 14, 20,  0,  0,  9, 18, 20])

5

20

array([  5,  20, 888,  14,  20,   0,   0,   9,  18,  20])

For multidimensional arrays, indexes are provided as tuples of integers:

In [13]:
a = np.diag([5,10,15])
a
a[1, 1]
a[2, 1] = 10 # third row, second column
a
a[0]

array([[ 5,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 15]])

10

array([[ 5,  0,  0],
       [ 0, 10,  0],
       [ 0, 10, 15]])

array([5, 0, 0])

When using multidimensional array, omitting the index in a dimension is interpreted by taking all elements in the unspecified dimensions.

In [27]:
a
a[1] # second row 

b=np.arange(1,28).reshape((3,3,3))
b
b[0]
b[0,1]

array([[ 5,  0,  0],
       [ 0, 10,  0],
       [ 0, 10, 15]])

array([ 0, 10,  0])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([4, 5, 6])

<a id="II.1.1"></a>
#### II.1.1 Random functions and seeds 

The __np.random.seed()__ method is used to initialize the default pseudorandom number generator in Python.<br>

The random module uses the seed value as a base to generate a random number. If a seed value is not provided it takes system current time. <br>
If you provide the same seed value before generating random data it will produce the same data (this could be useful while testing your code to regenerate the same sequence of pseudo-random numbers each time). 

If you want to set the seed that calls to __np.random...__ will use, you should use the __np.random.seed()__ function.

Another way to generate, each time, the same serie of pseudo-random numbers is to create a __np.random.RandomState()__ object (it's a random number generator). <br>
This object does not have any effect on the freestanding functions in __np.random__, but must be used explicitly.


In [28]:
rdst=np.random.RandomState(1234)
rdst.uniform(0, 10, 5)
np.random.seed(1234)
np.random.uniform(0, 10, 5)

array([1.9151945 , 6.22108771, 4.37727739, 7.85358584, 7.79975808])

array([1.9151945 , 6.22108771, 4.37727739, 7.85358584, 7.79975808])

<a id="II.2"></a>
### II.2 Slicing Arrays

Like other Python sequences, arrays can be sliced.<br>

<a id="II.2.1"></a>
#### II.2.1 Slicing One-dimensional arrays

In [14]:
x = np.arange(10)
x
x[:5]  # first five elements
x[5:8] # elements at position 5, 6 and 7 (but not 8)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4])

array([5, 6, 7])

<a id="II.2.2"></a>
#### II.2.2 Slicing Multi-dimensional arrays

Slicing Multi-dimensional arrays work in the same way as slicing one dimensional arrays: you provide multiple slices separated by commas:

In [15]:
np.random.seed(0)  # seed for reproducibility
y = np.random.randint(10, size=(3, 4))  # Two-dimensional array
y
y[:2, :3]  # two first rows, three first columns
y[:, ::2]  # all rows, every odd columns

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

array([[5, 0, 3],
       [7, 9, 3]])

array([[5, 3],
       [7, 3],
       [2, 7]])

<a id="II.2.3"></a>
#### II.2.3 Accessing rows and columns of matrices

Accessing a single row or column of a n-dimensional array can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [15]:
y = np.random.randint(10, size=(3, 4))  # Two-dimensional array
y
y[:, 0]  # first column of y
y[0, :]  # first row of x2
y[0]

array([[0, 4, 7, 8],
       [1, 6, 2, 2],
       [1, 3, 5, 8]])

array([0, 1, 1])

array([0, 4, 7, 8])

array([0, 4, 7, 8])

In the case of row access, the empty slice can be omitted:

In [32]:
y[0] # <=> y[0, :] 

array([8, 8, 1, 6])

The ellipsis constant represented by **...** means in numpy arrays "<i>at this point, insert as many full slices (:) to extend the multi-dimensional slice to all dimensions</i>".

__Note__: the method __flatten()__ returns a copy of an array collapsed into one dimension. 

__Note__: the method __ravel()__ returns a "view" of an array collapsed into one dimension. 

In [33]:
a = np.arange(16).reshape(2,2,2,2)
a
a[...,0].flatten()
# <=>
a[:,:,:,0].flatten()

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

array([ 0,  2,  4,  6,  8, 10, 12, 14])

array([ 0,  2,  4,  6,  8, 10, 12, 14])

<a id="II.2.4"></a>
#### II.2.4 Slices are views

One important – and extremely useful – thing to know about array slices is that they return __views__ rather than copies of the array data (this differs from Python list slicing: in lists, slices will be copies). <br>
Thus, when using slicing, the original array is not copied in memory, it also means that when modifying the view, the original array is modified as well.<br>
If you want to explicitly copy the data within an array or a subarray you can use the __copy()__ method.


In [34]:
y = np.random.randint(10, size=(3, 4))  # Two-dimensional array
y
slice1=y[0:2,2]
slice1
slice1[0]=99
y
slice2=y[0:2,2].copy()
slice2
slice2[0]=88
y


array([[4, 3, 0, 3],
       [5, 0, 2, 3],
       [8, 1, 3, 3]])

array([0, 2])

array([[ 4,  3, 99,  3],
       [ 5,  0,  2,  3],
       [ 8,  1,  3,  3]])

array([99,  2])

array([[ 4,  3, 99,  3],
       [ 5,  0,  2,  3],
       [ 8,  1,  3,  3]])

<a id="II.3"></a>
### II.3 Fancy indexing

NumPy arrays can be indexed with slices, but also with boolean (see § VII) or integer arrays (__masks__). 
This method is called __fancy indexing__. <br>

__Note__: _fancy indexing_ creates __copies not views__.

<a id="II.3.1"></a>
#### II.3.1 A first example

In [17]:
np.random.seed(3) # to generate each time the same random numbers
a = np.random.randint(0, 21, 15)
a
mask = (a % 3 == 0)
mask
extract_from_a = a[mask] # or,  a[a%3==0]
extract_from_a           # extract a sub-array with the mask

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False])

array([ 3,  0,  9,  6,  0, 12])

Indexing with a mask can be very useful to assign a new value to a sub-array.

<b>Note</b>: in the context of lvalue indexing (i.e. the indices are placed in the left hand side value of an assignment), no view or copy of the array is created (because there is no need to). 

In [18]:
a
a[a % 3 == 0] = -1
a # here a is updated
b=a[a == 10]
b # b is a copy of the selected a's elements
b[0]=100
b
a # here a is not updated

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14])

array([10, 10, 10])

array([100,  10,  10])

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14])

<a id="II.3.2"></a>
#### II.3.2 Indexing with a list of integers

Indexing can be done with an array or a <b>list of integers</b>.<br>

__Note__: the same index can be repeated several time
    

In [19]:
a = np.arange(0, 100, 10)
a
a[[2, 3, 2, 4, 2]] 

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

array([20, 30, 20, 40, 20])

In [38]:
a[[7, 9]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

The array of integer can be multi-dimensional, in this case the new array has the same shape as the array of integers.

In [39]:
idx=np.array([[1,2],[8,9]])
a[idx]

array([[  10,   20],
       [  80, -100]])

<a id="III"></a>
## III Concatenation/Splitting of arrays

<a id="III.1"></a>
### III.1 Concatenation of arrays

Concatenation of two or more arrays can be accomplished using the functions __concatenate()__, __vstack()__, __hstack()__ and __stack()__. <br><br>
__concatenate(seq [, axis=0])__ takes a tuple or list of arrays as its first argument, and concatenate them vertically (axis=0, the default) or horizontally (axis=1).<br>
__vstack(seq)__: stack its arrays arguments in sequence vertically (row wise) (<=> to np.concatenate(seq, axis=0))<br>
__hstack(seq)__: stack its arrays arguments in sequence horizontally (column wise) (<=> to np.concatenate(seq, axis=1))<br>
__stack(seq [, axis=0])__: stack its arrays arguments in sequence ***along a new axis*** (row wise by default)<br>

In [20]:
x = np.array([1, 2, 3])
x
y = np.array([4, 6, 8])
y
np.concatenate((x, y))
mat1= np.arange(1, 10).reshape((3, 3))
mat1
mat2= np.arange(20, 26).reshape((2, 3))
mat2
np.concatenate((mat1, mat2))
# <=>
np.vstack((mat1, mat2))

mat3= np.arange(31, 40).reshape((3, 3))
mat3
np.concatenate((mat1, mat3), axis=1)
# <=>
np.hstack((mat1, mat3))

array([1, 2, 3])

array([4, 6, 8])

array([1, 2, 3, 4, 6, 8])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[20, 21, 22],
       [23, 24, 25]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [20, 21, 22],
       [23, 24, 25]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [20, 21, 22],
       [23, 24, 25]])

array([[31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

array([[ 1,  2,  3, 31, 32, 33],
       [ 4,  5,  6, 34, 35, 36],
       [ 7,  8,  9, 37, 38, 39]])

array([[ 1,  2,  3, 31, 32, 33],
       [ 4,  5,  6, 34, 35, 36],
       [ 7,  8,  9, 37, 38, 39]])

In [32]:
x = np.array([[1, 2, 3],[4,5,6]])
x
x.shape
y = np.array([[4, 6, 8],[10,20,30]])
y
y.shape
res1=np.stack((x, y), axis=0)
res1
res1.shape
res2=np.stack((x, y), axis=-1)
res2
res2.shape


array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

array([[ 4,  6,  8],
       [10, 20, 30]])

(2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 4,  6,  8],
        [10, 20, 30]]])

(2, 2, 3)

array([[[ 1,  4],
        [ 2,  6],
        [ 3,  8]],

       [[ 4, 10],
        [ 5, 20],
        [ 6, 30]]])

(2, 3, 2)

<a id="III.2"></a>
### III.2 Splitting of arrays
The opposite of concatenation is splitting, which is implemented by the functions __split()__, __hsplit()__, and __vsplit()__. For each of these, we can pass a list of indices giving the split points (N split-points, leads to N + 1 subarrays).

In [20]:
x = [1, 2, 3, 44, 55, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
x1, x2, x3
mat1= np.arange(1, 10).reshape((3, 3))
mat1
x1, x2, x3 = np.split(mat1, [1,2])
x1, x2, x3
x1, x2, x3 = np.vsplit(mat1, [1,2])
x1, x2, x3
x1, x2, x3 = np.split(mat1, [1,2], axis=1)
x1, x2, x3
x1, x2, x3 = np.hsplit(mat1, [1,2])
x1, x2, x3

(array([1, 2, 3]), array([44, 55]), array([3, 2, 1]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

(array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]))

(array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]))

(array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]]))

(array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]]))

<a id="IV"></a>
## IV Universal functions (ufuncs)

Computation on NumPy arrays can be very fast if we use __vectorized operations__, generally implemented through NumPy's __universal functions__ (__ufuncs__).
Ufuncs can be used to make repeated calculations on array elements much more efficiently than via a traditional loop. Ufuncs are designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution.<br>
Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary ufuncs, which operate on two arguments.

<a id="IV.1"></a>
### IV.1 Numerical operations on arrays

<a id="IV.1.1"></a>
#### IV.1.1 Arithmetic operations on arrays

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators. The standard arithmetic operators (+, -, \*, /, //, %, **) can all be used:


In [21]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)
print("x**2 + x**3  = ", x**2 + x**3) # Operators can be combined

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]
x**2 + x**3  =  [ 0  2 12 36]


Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy: __add()__, __subtract()__, ...

In [44]:
print("x + 5 = np.add(x, 5) = ", np.add(x,5))

x + 5 = np.add(x, 5) =  [5 6 7 8]


<a id="IV.1.2"></a>
#### IV.1.2 Absolute value
The built-in absolute value function __abs()__ is also vectorized (it is an alias of __np.abs()__ and __np.absolute()__):

In [45]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)
np.absolute(x)

array([2, 1, 0, 1, 2])

array([2, 1, 0, 1, 2])

<a id="IV.1.3"></a>
#### IV.1.3 Trigonometric functions
NumPy provides a large number of Trigonometric ufuncs (__sin()__, __cos()__, __tan()__, ...):


In [46]:
theta = np.linspace(0, np.pi, 3)
theta
np.sin(theta)
np.cos(theta)
np.tan(theta)
x = [-1, 0, 1]
x
np.arcsin(x)
np.arccos(x)
np.arctan(x)

array([0.        , 1.57079633, 3.14159265])

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

[-1, 0, 1]

array([-1.57079633,  0.        ,  1.57079633])

array([3.14159265, 1.57079633, 0.        ])

array([-0.78539816,  0.        ,  0.78539816])

<a id="IV.1.4"></a>
#### IV.1.4 Exponents and logarithms
Another common type of ufunc operations are the exponentials and their inverse the logarithms:


In [23]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

def f(a):
    return np.cos(a)+np.sin(a)

f(x)

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
ln(x)    = [0.         0.69314718 1.09861229]
log2(x)  = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


array([ 1.38177329,  0.49315059, -0.84887249])

<a id="IV.1.5"></a>
#### IV.1.5 Other Ufuncs

Many other ufuncs are available in __numpy__, including hyperbolic trig functions, bitwise arithmetic, comparison operators, conversions from radians to degrees, rounding and remainders, and much more. <br>
Another excellent source for more specialized and obscure ufuncs is the submodule __scipy.special__: gamma functions, error functions, ...

<a id="IV.2"></a>
### IV.2 Advanced Ufunc Features

<a id="IV.2.1"></a>
#### IV.2.1 Specifying output

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. For all ufuncs, this can be done using the __out__ argument of the function:

In [48]:
x = np.arange(5)
y = np.empty(5)
result=x*10
np.multiply(x, 10, out=y)
y
z = np.zeros(10)
np.power(2, x, out=z[::2])
z # More efficient than y[::2] = 2 ** x

array([ 0., 10., 20., 30., 40.])

array([ 0., 10., 20., 30., 40.])

array([ 1.,  2.,  4.,  8., 16.])

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

<a id="IV.2.2"></a>
#### IV.2.2 Aggregates

For binary ufuncs, if we'd like to reduce an array with a particular operation, we can use the __reduce()__ method of any ufunc. <br>
A reduce repeatedly applies a given operation to the elements of an array until only a single result remains:<br>
calling reduce on the _add()_ ufunc returns the sum of all elements in the array,<br>
calling reduce on the _multiply()_ ufunc results in the product of all array elements,<br>
...<br>

In [49]:
x = np.arange(1, 6)
x
np.add.reduce(x)
np.multiply.reduce(x)

array([1, 2, 3, 4, 5])

15

120

If we'd like to store all the intermediate results of the computation, we can instead use __accumulate()__:

In [50]:
np.add.accumulate(x)
np.multiply.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

array([  1,   2,   6,  24, 120], dtype=int32)

__Note__:there are dedicated NumPy functions to obtain the same results (__np.sum()__, __np.prod()__, __np.cumsum()__, __np.cumprod()__).

In [51]:
np.sum(x)
np.prod(x)
np.cumsum(x)
np.cumprod(x)

15

120

array([ 1,  3,  6, 10, 15], dtype=int32)

array([  1,   2,   6,  24, 120], dtype=int32)

<a id="IV.2.3"></a>
#### IV.2.3 Outer products

Finally, any ufunc can compute the output of all pairs of two different inputs using the __outer()__ method. This allows you, in one line, to do things like create a multiplication table:


In [52]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

Another extremely useful feature of ufuncs is the ability to operate between arrays of different sizes and shapes, a set of operations known as __broadcasting__.

<a id="V"></a>
## V Broadcasting

Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

<a id="V.1"></a>
### V.1 First examples

Thanks to ufuncs, for arrays of the same size, binary operations are performed on an element-by-element basis. But as easily as, for instance, we can add to one-dimensional arrays we can add a one-dimensional to a scalar:

In [33]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b # OK: a and b have the same shape
a + 5 # OK 5 is broadcasted this is equivalent to a + np.array([5, 5, 5]) but without 
      # duplication of 5

array([5, 6, 7])

array([5, 6, 7])

In the same way we can add a one-dimensional array to a two-dimensional array:


In [34]:
M = np.ones((3, 3))
M
a
M + a # a is broadcasted across the second dimension in order to match the shape of M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

More complicated cases can involve broadcasting of both arrays to match a common shape:

<img src="nbimages/broadcasting.png" alt="Broadcasting" title="Broadcasting" width=600 height=400 />


In [55]:
a= np.arange(3).reshape(3,1)
b= np.arange(3)
a 
a.shape # (3,1) -> will be broadcasted to (3,3)
b
b.shape # (3,) -> will be broadcasted to (3,3)
c=a+b
c
c.shape # (3,3)

array([[0],
       [1],
       [2]])

(3, 1)

array([0, 1, 2])

(3,)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

(3, 3)

<a id="V.2"></a>
### V.2 Broadcasting rules

When operating on two arrays, to determine if broadcasting is possible, NumPy compares their shapes element-wise to determine if their dimensions are __*compatibles*__.
It starts with the trailing dimensions, and works its way forward.<br> 
Two dimensions are compatible when __they are equal__, or __one of them is 1__.

If these conditions are not met, an exception is raised.<br>

__Note__: arrays do not need to have the same number of dimensions. __If a dimension is missing it is considered as being 1__.<br>

When either of the dimensions compared is 1, the other is used: __dimensions with size 1 are stretched or "broadcasted" to match the other__.

In [35]:
M = np.ones((2, 3))
a = np.arange(3)
M
M.shape # (2,3)
a
a.shape # (3,) -> broadcasted to (1,3) then to (2,3)
M+a # Broadcast is OK !

b=10 # Here the shape is considered as being (1,) -> broadcasted to (1,1) then to (2,3)
M+b # Broadcast is OK !

c = np.arange(4)
c
c.shape # (4,) The last dimension of a is 4 it should be 3 (last dimension of M) or 1
M+c # Broadcast Error !

array([[1., 1., 1.],
       [1., 1., 1.]])

(2, 3)

array([0, 1, 2])

(3,)

array([[1., 2., 3.],
       [1., 2., 3.]])

array([[11., 11., 11.],
       [11., 11., 11.]])

array([0, 1, 2, 3])

(4,)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

<a id="VI"></a>
## VI Boolean Masking of Arrays

__Masking__ comes up when you want to extract, modify, count, or otherwise manipulate values in an array based on some criterion: for example, you might wish to count all values greater than a certain value, or perhaps remove all outliers that are above some threshold. <br>

In NumPy, __boolean masking__ is often the most efficient way to accomplish these types of tasks: we can use different ufuncs to do element-wise comparisons over arrays, and we can then manipulate the results to answer the questions we have.

<a id="VI.1"></a>
### VI.1 Comparison Operators as ufuncs

NumPy implements comparison operators such as __<__, __>__, __>=__, __<=__, __==__, __!=__, as element-wise ufuncs (__np.less()__, __np.greater()__, ...).<br>

These will work on arrays of any size and shape. <br>

The result of these comparison operators is always an array with a Boolean data type. 


In [36]:
x = np.array([1, 2, 3, 4, 5])
x < 3  # less than
x > 3  # greater than
x >= 3  # greater than or equal

array([ True,  True, False, False, False])

array([False, False, False,  True,  True])

array([False, False,  True,  True,  True])

It is also possible to do an element-wise comparison of two arrays, and to include compound expressions:

In [37]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

<a id="VI.2"></a>
### VI.2 Working with Boolean Arrays

Given a Boolean array, there are several useful operations you can do. 

To __count the number of True entries__ in a Boolean array, __np.count_nonzero()__ is available (another way to get at this information is to use __np.sum()__).

__Note__: the benefit of _np.sum()_ is that the summation can be done along rows or columns as well.


In [24]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x
x<6
np.count_nonzero(x < 6)
np.sum(x < 6)
np.sum(x < 6, axis=1)
np.sum(x < 6, axis=0)

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

8

8

array([4, 2, 2])

array([2, 2, 2, 2])

To check whether any or all the values are true, we can use __np.any()__ or __np.all()__.
__np.any()__ or __np.all()__ can be used along particular axes as well:


In [ ]:
# are there any values greater than 8?
np.any(x > 8)
# are all values positive or zero?
np.all(x >= 0)
# are all values in each row less than 8?
np.all(x < 8, axis=1)

<a id="VI.3"></a>
### VI.3 Boolean operators

You can combine comparison operators with the help of Boolean operators.
The Boolean operators are provided through the following Python's operators: __&__ (and), __|__ (or), __^__ (exclusive or), and __~__ (not).<br>

Each of them is implemented by a specific Numpy Ufunc: __np.bitwise_and()__, __np.bitwise_or()__, ...
<br>Combining comparison operators and Boolean operators on arrays lead to a wide range of efficient logical operations.

In [ ]:
x
# how many elements in x are in the range [0, 5]
np.sum((x>=0) & (x<=5))
# how many elements in x are not in the range [0,5]
np.sum(~ ((x>=0) & (x<=5)))

<a id="VI.4"></a>
### VI.4 Boolean Arrays as Masks

A Boolean arrays can be used as a __mask__, to select a particular subsets an array:<br>

*array[boolean_array_mask]*<br>

What is being returned is an array filled with all the values in positions at which the mask array is True.

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x[x<5] # select all values that are less than 5

# construct a mask of all summer days (June 21st is the 172nd day)
days = np.arange(365)
summer = (days > 172) & (days < 262)
days[summer] # summer days
days[~summer] # not summer days


<a id="VII"></a>
## VII Basic Linear Algebra Operations

<a id="VII.1"></a>
### VII.1 Dot product

We can compute the dot product of two NumPy arrays using the __np.dot()__ function.


In [25]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([1,2,3])
a
b
np.dot(a,b)

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3])

array([14, 32])

<a id="VII.2"></a>
### VII.2 Transpose of a matrix

We can transpose a matrix with the help of the __np.transpose()__ function or the __transpose()__ method.

__Note__: the attribute __T__ is an alias of _transpose()_.


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a
a.transpose()
a.T
np.transpose(a)

<a id="VII.3"></a>
### VII.3 Inverse of a Matrix

Finding an inverse of a matrix A, if it exists, is finding a matrix B such that the product of A with B is the identity matrix. <br>
NumPy’s __linalg__ module has the function __inv()__ to find the inverse of a matrix.


In [ ]:
b = np.array([[1.,2.,3.], [10.,5,6.],[7.,8.,9.]])
b
np.linalg.inv(b)

<a id="VII.4"></a>
### VII.4 Matrix Multiplication

We can use NumPy’s __np.dot()__ function to compute matrix multiplication.<br>
    
__Note__: __np.allclose()__ function is used to find if two arrays are element-wise equal within a tolerance (the tolerance values are positive very small numbers)


In [ ]:
np.allclose(np.dot(b, b_inv), np.eye(3))

<a id="VII.5"></a>
### VII.5 And also

__np.trace()__: compute the trace of a matrix.<br>
__np.linalg.det()__: compute the determinant of a matrix.<br>
__np.linalg.eig()__: compute the Eigen Value and Eigen Vector of a matrix.<br>


<a id="VIII"></a>
## VIII NumPy Aggregate Functions

In Python NumPy module, we have many aggregate functions, or statistical function to work with a single dimensional or multi-dimensional arrays. 

<a id="VIII.1"></a>
### VIII.1  Minimum and Maximum

Numpy has built-in __min()__ and __max()__ functions, to find the minimum value and maximum value of any given array (instead of the function you can use methods with the same name of the array object itself):

In [ ]:
rng = np.random.RandomState(5)
x = rng.randint(25, size=(5, 5))
x
np.min(x)
x.min()

Aggregation functions take an additional argument specifying the axis along which the aggregate is computed. For example, we can find the minimum value within each column by specifying __axis=0__:

__Note__: _axis=0_ means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.


In [ ]:
M = np.random.random((3, 4))
M
M.min()
M.min(axis=0)

<a id="VIII.2"></a>
### VIII.2 Other aggregate functions

<table border=1>
<tr><th>Function Name</th><th>NaN-safe Version</th><th>Description</th></tr>
<tr>
<td style="text-align:left"><b>np.sum</b></td>
<td style="text-align:left"><b>np.nansum</b></td>
<td style="text-align:left">Compute sum of elements</td>
</tr>
<tr>
<td style="text-align:left"><b>np.prod</b></td>
<td style="text-align:left"><b>np.nanprod</b></td>
<td style="text-align:left">Compute product of elements</td>
</tr>
<tr>
<td style="text-align:left"><b>np.mean</b></td>
<td style="text-align:left"><b>np.nanmean</b></td>
<td style="text-align:left">Compute mean of elements</td>
</tr>
<tr>
<td style="text-align:left"><b>np.std</b></td>
<td style="text-align:left"><b>np.nanstd</b></td>
<td style="text-align:left">Compute standard deviation</td>
</tr>
<tr>
<td style="text-align:left"><b>np.var</b></td>
<td style="text-align:left"><b>np.nanvar</b></td>
<td style="text-align:left">Compute variance</td>
</tr>
<tr>
<td style="text-align:left"><b>np.min</b></td>
<td style="text-align:left"><b>np.nanmin</b></td>
<td style="text-align:left">Find minimum value</td>
</tr>
<tr>
<td style="text-align:left"><b>np.max</b></td>
<td style="text-align:left"><b>np.nanmax</b></td>
<td style="text-align:left">Find maximum value</td>
</tr>
<tr>
<td style="text-align:left"><b>np.argmin</b></td>
<td style="text-align:left"><b>np.nanargmin</b></td>
<td style="text-align:left">Find index of minimum value</td>
</tr>
<tr>
<td style="text-align:left"><b>np.argmax</b></td>
<td style="text-align:left"><b>np.nanargmax</b></td>
<td style="text-align:left">Find index of maximum value</td>
</tr>
<tr>
<td style="text-align:left"><b>np.median</b></td>
<td style="text-align:left"><b>np.nanmedian</b></td>
<td style="text-align:left">Compute median of elements</td>
</tr>
<tr>
<td style="text-align:left"><b>np.percentile</b></td>
<td style="text-align:left"><b>np.nanpercentile</b></td>
<td style="text-align:left">Compute rank-based statistics of elements</td>
</tr>
<tr>
<td style="text-align:left"><b>np.any</b></td>
<td style="text-align:left"><b>N/A</b></td>
<td style="text-align:left">Evaluate whether any elements are true</td>
</tr>
<tr>
<td style="text-align:left"><b>np.all</b></td>
<td style="text-align:left"><b>N/A</b></td>
<td style="text-align:left">Evaluate whether all elements are true</td>
</tr>
<table>

<a id="IX"></a>
## IX Some other useful functions

To finish this overview of Python NumPy's array, let's have a look at a few remaining useful functions. 

<a id="IX.1"></a>
### IX.1  where

The **numpy.where(condition[, x, y])** function returns the indices of elements in an input array where the given *condition* is satisfied.<br>

Parameters:<br>
**condition** : When True, yield *x*, otherwise yield *y*.<br>
**x, y** : Values from which to choose (*x*, *y* and *condition* need to be broadcastable to some shape).<br>

Returns:<br>
*where()* returns a ndarray (or tuple of ndarrays).<br>
If both *x* and *y* are specified, the output array contains elements of *x* where condition is True, and elements from *y* elsewhere.<br>
If only *condition* is given, return the indices (tuple of arrays) where condition is True.<br>


In [26]:
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
result = np.where((arr > 12) & (arr < 16))
result
arr[result]

(array([ 2,  3,  4,  7, 10, 11], dtype=int64),)

array([13, 14, 15, 15, 14, 15])

In [27]:
a = np.arange(9).reshape((3, -1))
a
np.where(a < 4, -1, 100)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ -1,  -1,  -1],
       [ -1, 100, 100],
       [100, 100, 100]])

In [28]:
np.where(a < 4, a, 100)

array([[  0,   1,   2],
       [  3, 100, 100],
       [100, 100, 100]])

In [29]:
np.where(a < 4, a + 10, a)

array([[10, 11, 12],
       [13,  4,  5],
       [ 6,  7,  8]])

In [30]:
np.where(a < 4)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [31]:
list(zip(*np.where(a < 4)))

[(0, 0), (0, 1), (0, 2), (1, 0)]

<a id="IX.2"></a>
### IX.2  repeat

The **numpy.repeat(arr, repetitions, axis = None)** function is used to repeat elements of an array.<br>

Parameters:<br>
**a**       : Input array. <br>
**repeats** : No. of repetitions of each array elements along the given axis.<br>
**axis**    : Axis along which we want to repeat values. By default, it returns a flat output array.<br>

Returns:<br>
An output array which has the same shape as a, except along the given axis.<br><br>

In [32]:
np.repeat(a = 7, repeats = 4)
np.repeat(7, 4)
np.repeat(a = [6,7], repeats = 2)

array([7, 7, 7, 7])

array([7, 7, 7, 7])

array([6, 6, 7, 7])

In [33]:
mat=np.array([[6,7],[8,9]])
mat
np.repeat(mat, 2)
np.repeat(mat, 2, axis=0)
np.repeat(mat, 2, axis=1)

array([[6, 7],
       [8, 9]])

array([6, 6, 7, 7, 8, 8, 9, 9])

array([[6, 7],
       [6, 7],
       [8, 9],
       [8, 9]])

array([[6, 6, 7, 7],
       [8, 8, 9, 9]])

In [34]:
arr=np.array([1,2,3,4])
arr
arr=arr[np.newaxis, :] # <=> arr=np.expand_dims(arr, axis = 0)
arr
np.repeat(arr, 2, axis=0)

array([1, 2, 3, 4])

array([[1, 2, 3, 4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

<a id="IX.3"></a>
### IX.3  tile

The **numpy.tile(a, reps)** function is used to constructs an array by repeating the parameter *a*  (an array like object) the number of times specified by the *reps* parameter.<br>

Parameters:<br>
**a**       : Input array. <br>
**reps**    : If you provide an integer *n* to *reps*, then it will simply copy the array n times, horizontally.<br>
You can also pass an 'array like' object to *reps*.
When you do so, the first number is the number of repeats downwards and the second number in the tuple is the number of repeats across.
And if you have more than two numbers, it will actually repeat into a greater number of dimensions.<br>

Returns:<br>
A new array.<br><br>

In [35]:
np.tile(A = [6,7,8], reps = 2)
np.tile(A = [6,7,8], reps = (2,1))
np.tile(A = [6,7,8], reps = (2,2))

array([6, 7, 8, 6, 7, 8])

array([[6, 7, 8],
       [6, 7, 8]])

array([[6, 7, 8, 6, 7, 8],
       [6, 7, 8, 6, 7, 8]])

<a id="IX.4"></a>
### IX.4  delete

The **numpy.delete(arr, obj, axis=None)** function returns a new array with the specified subarray deleted from the input array.
<br>

Parameters:<br>
**arr**       : Input array. <br>
**obj**    : Can be a slice, an integer or array of integers, indicating the subarray to be deleted from the input array.<br>
**axis**    : Axis to delete: if the axis parameter is not used, the input array is flattened.

Returns:<br>
A new array (a copy of *arr* with the elements specified by *obj* removed).<br><br>

In [38]:
a = np.arange(12).reshape(3, 4)
a
r_del = np.delete(a, 1, axis=0)
r_del
c_del = np.delete(a, 1, axis=1)
c_del
o_del = np.delete(a, 1)
o_del

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a = np.arange(12).reshape(3, 4)
a
r_del = np.delete(a, [0,1], axis=0)
r_del
c_del = np.delete(a, [0,1], axis=1)
c_del
o_del = np.delete(a, [0,1])
o_del

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 8,  9, 10, 11]])

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

<a id="IX.5"></a>
### IX.5  unique

The **numpy.unique()** function is used to find (and return) the unique elements of an array.
<br><br>
There are three optional outputs in addition to the unique elements:<br>

the indices of the input array that give the unique values (if the optional parameter <b>return_index</b> is True)
<br>the indices of the unique array that reconstruct the input array (if the optional parameter <b>return_inverse</b> is True)
<br>the number of times each unique value comes up in the input array if the optional parameter <b>return_count</b> is True)
<br>


In [40]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
a
values, counts = np.unique(a, return_counts=True)
values
counts

array([1, 2, 6, 4, 2, 3, 2])

array([1, 2, 3, 4, 6])

array([1, 3, 1, 1, 1], dtype=int64)

<a id="IX.6"></a>
### IX.6  setdiff1d

The **numpy.setdiff1d(ar1, ar2)** function is used to find the set difference of two 1 dimentional arrays: it returns, as an array, the unique values in <b>ar1</b> that are not in <b>ar2</b>.

In [17]:
import numpy as np
a1 = np.array([0, 10, 20, 40, 60, 80])
a2 = [10, 30, 40, 50, 70]
print(f"Unique values in {a1} that are not in {a2} are: {np.setdiff1d(a1, a2)}")


Unique values in [ 0 10 20 40 60 80] that are not in [10, 30, 40, 50, 70] are: [ 0 20 60 80]


<a id="IX.7"></a>
### IX.7  append and insert

A NumPy array does not have a built-in append method. Instead, to append elements to a NumPy array, use the **numpy.append(arr, values, axis=None)** function.

Note that *append()* does not occur in-place: a new array is allocated and filled. If *axis* is `None`, *append()* returns a flattened array.



In [3]:
mat=[[0, 1, 2], [3, 4, 5]]
np.append(mat,[[6, 7, 8]], axis=0)
np.append(mat,[[6, 7, 8]])
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

[[0, 1, 2], [3, 4, 5]]

The **numpy.insert(arr, indices, values, axis=None)** function is used to insert values along the given axis before the given indices.

Note that *insert()* does not occur in-place: a new array is allocated and filled. If *axis* is `None`, *insert()* returns a flattened array.

In [6]:
mat=[[0, 1, 2], [3, 4, 5]]
np.insert(mat, 2, 10)
np.insert(mat, 2, 10, axis=1)
mat


array([ 0,  1, 10,  2,  3,  4,  5])

array([[ 0,  1, 10,  2],
       [ 3,  4, 10,  5]])

[[0, 1, 2], [3, 4, 5]]